[package]
name = "tartarus-hetzner"
description = "Hetzner Cloud session provider for Tartarus."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tartarus-provider = { path = "../tartarus-provider" }

reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
